name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t wechat-bot
    - name: build
      run: docker run -d --rm --name wechat-bot -v $(pwd)/.env:/app/.env wechat-bot
